In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
df = pd.read_csv('glassdoor_jobs_cleared_data.csv')
#df.head()
df.columns
## job title and seniority

## fix state los angeles # not in mine

## Job description length

## Competitor Count

## hourly wage of annaul

## remove new line from job title

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Salary_type', 'min_salary', 'max_salary', 'avg_salary', 'Company_text',
       'job_city', 'job_state', 'same_state', 'company_age', 'python_JD',
       'rstudio_JD', 'spark_JD', 'aws_JD', 'machinelearning_JD',
       'datascience_JD'],
      dtype='object')

In [4]:
#df.job_state.value_counts()
df['Job Description']

0      Secure our Nation, Ignite your FutureSummaryTh...
1      GENERAL DESCRIPTIONIndividuals working as busi...
2      GEICO’s Data Science team uses predictive anal...
3      Who We AreWere Americas largest mortgage lende...
4      JobSummaryApply several forms of statistical m...
                             ...
484    The Lead Certified Clinical Laboratory Scienti...
485    With one application you can be considered for...
486    Analytics ManagerJob DescriptionWe are looking...
487    Data Scientist / Quantitative Researcher – Hig...
488    Data Science Developer(Job Number:049829)Descr...
Name: Job Description, Length: 489, dtype: object

In [5]:
df[df['Job Description'].str.contains('Engineer')][['Job Description','Job Title']]

,Job Description,Job Title
8,"By clicking the Apply button, I understand tha...",Data Scientist
13,MITRE performs leading-edge researchand develo...,Artificial Intelligence/Machine Learning Data ...
14,Cohere Health is simplifying healthcare for pa...,Data Scientist
18,Posting TitleData Scientist – Causal & Predict...,Data Scientist – Causal & Predictive analytics...
24,POSITION PURPOSE:The Data Architect/Data Model...,Data Modeler
...,...,...
481,"Company DescriptionPaying the right way, getti...",Senior Data Engineer
482,"Job DescriptionAt Shipt, we are transforming t...",Machine Learning Engineer
483,"Machine Learning EngineerAurora, COApply NowAr...",Machine Learning Engineer
487,Data Scientist / Quantitative Researcher – Hig...,Data Scientist / Quantitative Researcher – Hig...
488,Data Science Developer(Job Number:049829)Descr...,Data Science Developer

##### added new columns
1. job_simplifier
2. seniority
3. desc_len
4. competiters_count

###### replaced 'los angeles' with CA in states
##### doubled min_salary with 2 where hourly rate == 1
##### removed "\n" from company_text

##### check df.describe()

### check distribution and outliers

pd.Rating.hist() <br></br>
pd.avg_salary.hist() <br></br>
pd.desc_len.hist() <br></br>
pd.boxplot(column = ['avg_salary', 'desc_len', 'Rating', 'age'])  <span style="color:red;"> -->> check boxplot </span> <br></br>
pd.boxplot(column = ['avg_salary', 'Rating', 'age']) <br></br>
pd.boxplot(column = 'Rating') <br></br>
<br></br>
### now check coorelation between out continous variables
df[['age','avg_salary','Rating','desc_len','competiters_count']].corr() <br></br>
<br></br>
### used seaborn's heatmap for plotting the coorelation
sns.heatmap(df[[''age','avg_salary','Rating','desc_len','competiters_count']].corr(), vmax = .3, center=0, square=True, linewidth=.5, cbar_kws={"shrink":5}) <br></br>
<br></br>
### coorelation and bar charts in categorical data
df_cat = df[['Location','Headquarters','Size','Type of ownership','Industry','Sector','Revenue','comoany_txt','job_state','spark','aws','excel','job_simp','seniority']] <br></br>
<br></br>
for i in df_cat.columns(): <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cnts = df_cat[i].value_counts() <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print('Plot for %S , Total count: %d' % (i, len(cnts))) <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; chart = sns.barplot(x= cnts.index, y= cnts) <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; chart.set_xticklabels(chart.get_set_xticklabels(), rotation=90) <span style="color:green;"> -->> This is for rotation of x axis </span> <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; plt.show() <br></br>
    
##### few graphs are looking messy due to huge data so lets create graph for top 20 records
<br></br>
for i in df_cat[['Location','Headquarters','company_txt']].columns(): <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cnts = df_cat[i].value_counts()[:20] <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print('Plot for %S , Total count: %d' % (i, len(cnts))) <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; chart = sns.barplot(x= cnts.index, y= cnts) <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; chart.set_xticklabels(chart.get_set_xticklabels(), rotation=90) <span style="color:green;"> -->> This is for rotation of x axis </span> <br></br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; plt.show() <br></br>
    
<br></br>
### check pivot table to see the salary by different columns
pd.pivor_table(df, index = 'job_simplifier', values = 'avg_slary')
pd.pivor_table(df, index = ['job_simplifier','Seniority'], values = 'avg_slary')

pd.pivor_table(df, index = 'job_state', values = 'avg_slary').sort_values('avg_salary', ascending = False)



pd.set_option('display.max_rows', None)

pd.pivot_table(df, index = ['job_state','job_simplifier'], values = 'avg_slary').sort_values('job_state', ascending = False)

pd.pivot_table(df, index = ['job_state','job_simplifier'], values = 'avg_slary', aggfunc = 'count').sort_values('job_state', ascending = False)

pd.pivot_table(df[df.job_simplifier == 'Data Scientist'], index = 'job_state', values = 'avg_slary').sort_values('avg_slary', ascending = False)


##### Salary X Rating, industry , sector, revenue, competiters_count, hourly, employer provided, python, r, spark, aws, excel, desc_learn, type of ownership

df_pivot = df[df['Rating','Industry','Sector','Revenue','competiters_count','hourly','employer_provided','python_yn','R_yn','spark','aws','excel','Type of ownership','avg_salary']]

for i in df_pivot.columns:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print(i)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print(pd.pivot_table(df_pivot,index = i, value = 'avg_salary').sort_values('avg_salary', ascending = False))


## Descriptive analysis for company description
from wordcloud import WordCloud, ImageColorGenerator, STOPWORDS <br></br>
from nltk.corpuc import stopwords <br></br>
form nltk. tokenize import word_tokenize <br></br>

words = " ".join(df['Job Description']) <br></br>

def punctuation_stop(text): <br></br>
&nbsp;&nbsp;&nbsp;&nbsp; """ remove punctuation and stop word """ <br></br>
&nbsp;&nbsp;&nbsp;&nbsp; filtered = [] <br></br>
&nbsp;&nbsp;&nbsp;&nbsp; stop_words = set(stopwords.words('english')) <br></br>
&nbsp;&nbsp;&nbsp;&nbsp; word_tokens = word_tokenize(text) <br></br>
&nbsp;&nbsp;&nbsp;&nbsp; for w in word_tokens: <br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if w not in stop_words and w.isalpha() <br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;filtered.append(w.lower()) <br></br>
&nbsp;&nbsp;&nbsp;&nbsp; return filtered <br></br>
 <br></br>

word_filetered = punctuation_stop(words) <br></br>
text = " ".join([ele for ele in word_filtered]) <br></br>
wc = WordCloud(background_color="white", random_state=1, stopwords=STOPWORDS, max_words=2000, width=800, height=1500) <br></br>
wc.generate(text) <br></br>

plt.figure(figsize=[10,10]) <br></br>
plt.imshow(wc, interpolation="bilinear") <br></br>
plt.axis('off') <br></br>
plt.show() <br></br>


<br></br><br></br>
git add . <br></br>
git commit -m 'added data eda jupyter notebook'<br></br>
git push<br></br>
git push --set-upstream origin data_eda<br></br>
go to git hub and create new pull request to merge it in master branch